### ISSUE TITLE
AcrnGT holding forcewake lock cause high cpu usage gvt workload thread.

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#3280]
AcrnGT holding forcewake lock cause high cpu usage gvt workload thread

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4089

**Comment by minhe1** [comment]
More detailed information about this issue:
The i915 forcewake mechanism is to keep the GPU from its low power state, in order to access some specific registers.  However, in the path of GVT-g scheduler submission, there's no need to acquire the i915 forcewake. If removing it, we can reduce some CPU usage of the gvt workload thread in SOS.

**Comment by Mingyuan18** [comment]
Cannot reproduce this issue, so close it.
ClearLinux version: 30110
ACRN tag: acrn-2019w26.3-140000p
