### ISSUE TITLE
AcrnGT emulation thread causes high cpu usage when shadowing ppgtt

### ISSUE THREAD

**Issue by Mingyuan18** [projectacrn/acrn-hypervisor#3281]
AcrnGT emulation thread causes high cpu usage when shadowing ppgtt

**Comment by Mingyuan18** [comment]
[External_System_ID] ACRN-4091

**Comment by minhe1** [comment]
More detailed information about this issue:
In current design, when guest updating its PPGTT table, GVT-g may call gfn_to_mfn frequently. So there's some performance improvement space by optimizing the gfn_to_mfn function call.
However, this commit is not well designed, and we may refactor the VHM module later. So this commit can be dropped. And we can close this issue as "won't fix" since we will have better designed solution in the near future.

**Comment by Mingyuan18** [comment]
Close this issue as "won't fix".
