### ISSUE TITLE
one of screen got fuzzing on up2 board

### ISSUE THREAD

**Issue by nwang-intel** [projectacrn/acrn-hypervisor#413]
we follow the GSG guide and installed hypervisor with ClearLinux 22850 as SOS on up2 board, when booting system with hypervisor we got one of screen fuzzing. 
we didn't see this issue when we boot the system to native OS, so clearly it is not hardware issue.
we also revert the version back to 21260 or 21530 and we didn't see this issue when we boot system with hypervisor. 
![fuzzing screen](https://user-images.githubusercontent.com/36183512/41333890-052bd148-6f16-11e8-8835-e164e772257d.jpg)

**Comment by gvancuts** [comment]
@kiendinh @ttzeng , did you see this too?

**Comment by ttzeng** [comment]
@gvancuts I observed the same symptom and it is because the pipe-B and pipe-C are default assigned to the UOS. Once you launch the UOS, it will show the UOS console. FYI

**Comment by jren1** [comment]
@shiqingg Can you take a look?

**Comment by shiqingg** [comment]
This issue is reproducible with latest hypervisor and kernel in github.

At the very beginning of the SOS boot-up, two displays are shown the same messages with linux logo. 
Right after the kernel message '[    0.744221] fb: switching to inteldrmfb from EFI VGA', one of the displays got messed up.

Will do more investigation.

**Comment by shiqingg** [comment]
With Jiang Fei's great help, this issue got clarified.

Here is the reason that we see the different behavior before and after the kernel message "[ 0.744221] fb: switching to inteldrmfb from EFI VGA".
The console shown up on the HDMI or DP display is using Framebuffer.
At the begining of SOS boot-up, the console is shown on the display via EFI-based Framebuffer since Intel DRM Framebuffer is not loaded in kernel yet.
After Intel DRM Framebuffer is loaded successfully in kernel, the console is shown on the display via Intel DRM Framebuffer.

Clone mode is not supported well within Intel DRM Framebuffer.
When UOS is not launched, the two displays are using same Framebuffer.
The content on the second display is cloned from the first one. When the resolution of these two displays are different, the content on the second display got messed up.

After UOS is launched, each of SOS and UOS will own one Framebuffer. It means that one Framebuffer for one display.
So that the second display is showing the console of UOS with nice looking.

If we disable the Intel DRM Framebuffer and start weston in SOS, we will see that both displays are working fine.
Here is the instruction:
1. Modify the following two items in acrn.conf
    i915.domain_plane_owners=0x011111100000
    i915.enable_initial_modeset=1
2. After SOS is booting up, start weston in SOS with the following command
    $ weston --tty=1 -i 0 &
At this moment, we will see that two displays are both working fine.

**Comment by gvancuts** [comment]
I think we should add a link to an extensive guide about all these i915 options that we have. Do you know if such guide exists and if so, where it can be found online?

@jren1 @dongyaozu

**Comment by dongyaozu** [comment]
Good suggestion, we should have document on all those usages.

**Comment by jren1** [comment]
Agree! We will document such options

**Comment by gvancuts** [comment]
Thanks!! (sorry I had missed your replies before reaching out to the mailing list...)

**Comment by mwang106** [comment]
This issue has been resolved.
