### ISSUE TITLE
Hard-coded installation path is being used !!

### ISSUE THREAD

**Issue by saininav** [projectacrn/acrn-hypervisor#4864]
Instead of hard-coded installation path, it should be set by variables, which allows the user to set custom path.

For example:
$(DESTDIR)/usr/bin/$(PROGRAM)
should be
$(DESTDIR)$(bindir)/$(PROGRAM)

Where variable can be set, like:
DESTDIR ?=
prefix ?= /usr
bindir ?= $(prefix)/bin

**Comment by saininav** [comment]
https://github.com/projectacrn/acrn-hypervisor/pull/4858

**Comment by fuzhongl** [comment]
[External_System_ID] ACRN-6404

**Comment by dbkinder** [comment]
Have you analyzed what will/might break if the default installation directories are changed by the user?

**Comment by fuzhongl** [comment]
@dbkinder  
Following id feedback from @saininav :
**Currently we are using default values set by yocto bitbake.conf and we do not change them while installing.
https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/conf/bitbake.conf#n18

You can keep below default values of variables in Makefiles.

DESTDIR ?=
prefix ?= /usr
bindir ?= $(prefix)/bin
libdir ?= $(prefix)/lib64
nonarchlibdir ?= $(prefix)/lib
datadir ?= $(prefix)/share
includedir ?= $(prefix)/include
systemd_unitdir ?= $(prefix)/lib/systemd 

We will not change them due to acrnlog.service or other limitations.

Regards,
Naveen**

Will use [this issue](https://github.com/projectacrn/acrn-hypervisor/issues/4892) to remind user to update relate service if he/she modify the default value of installation path.
