### ISSUE TITLE
{"launch config error":"Replacement index 1 out of range for positional args tuple"}

### ISSUE THREAD

**Issue by coveritytest** [projectacrn/acrn-hypervisor#7052]
**Describe the bug**
The error {"launch config error":"Replacement index 1 out of range for positional args tuple"} pops up when clicking on "Generate launch script" in http://127.0.0.1:5001/launch/shared_launch_6user_vm

**Comment by NanlinXie** [comment]
@coveritytest Could you explain more details about your issue, below template for your reference.

**Describe the bug**
A clear and concise description of what the bug is.

**Platform**
Describe the platform information, 

**Codebase**
Describe which codebase is used.

**Scenario**
Describe the scenario: Hybrid, Industry or logical_partition

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by fuzhongl** [comment]
@coveritytest Could you please help to have a try with the latest code?
Thanks!

**Comment by fuzhongl** [comment]
Closed since no feedback long time.
